; --------------
; SYSTEM PALETTE
; --------------
SYSTEM_PALETTE:
           ;$0BGR   ; #RR GG BB
    DC.W    $0000   ; ---------
    DC.W    $0A00   ; #00 00 00
    DC.W    $00A0   ; #00 48 00
    DC.W    $0AA0   ; #00 6C 00
    DC.W    $000A   ; #00 90 00
    DC.W    $0A0A   ; #00 B4 00
    DC.W    $005A   ; #00 D8 00
    DC.W    $0AAA   ; #00 00 48
    DC.W    $0555   ; #00 24 6C
    DC.W    $0F55   ; #24 48 90
    DC.W    $05F5   ; #24 6C B4
    DC.W    $0FF5   ; #48 90 D8
    DC.W    $055F   ; #6C B4 FF
    DC.W    $0F5F   ; #6C 24 24
    DC.W    $05FF   ; #90 48 24
    DC.W    $0FFF   ; #B4 6C 48
